In [ ]:
from pandas import read_csv
import pandas as pd
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [ ]:
filename = "/content/pima-indians-diabetes.data.csv"

In [ ]:
names = ["preg","plas","pres","skin","test","mass","pedi","age","class"]

In [ ]:
DataFrame = read_csv(filename,names=name)

In [ ]:
array = DataFrame.values

In [ ]:
DataFrame.head()

preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  0.627   50      1
1     1    85    66    29     0  26.6  0.351   31      0
2     8   183    64     0     0  23.3  0.672   32      1
3     1    89    66    23    94  28.1  0.167   21      0
4     0   137    40    35   168  43.1  2.288   33      1

In [ ]:
DataFrame.shape

(768, 9)

In [ ]:
X = array[:,0:8]
Y = array [:,8]

In [ ]:
test = SelectKBest(score_func=chi2,k=5)
fit = test.fit(X,Y)
set_printoptions(precision = 4)
print(fit.scores_)

[ 111.5197 1411.887    17.6054   53.108  2175.5653  127.6693    5.3927
  181.3037]


In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
x = pd.DataFrame(fit.scores_).T

In [ ]:
x

0            1          2  ...           5         6           7
0  111.519691  1411.887041  17.605373  ...  127.669343  5.392682  181.303689

[1 rows x 8 columns]

In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
x.columns=names[:8]
x

preg         plas       pres  ...        mass      pedi         age
0  111.519691  1411.887041  17.605373  ...  127.669343  5.392682  181.303689

[1 rows x 8 columns]

In [ ]:
sorted_x = x.sort_values(by=0,axis=1,ascending=False)

In [ ]:
sorted_x

test         plas         age  ...      skin       pres      pedi
0  2175.565273  1411.887041  181.303689  ...  53.10804  17.605373  5.392682

[1 rows x 8 columns]

In [ ]:
DataFrame

preg  plas  pres  skin  test  mass   pedi  age  class
0       6   148    72    35     0  33.6  0.627   50      1
1       1    85    66    29     0  26.6  0.351   31      0
2       8   183    64     0     0  23.3  0.672   32      1
3       1    89    66    23    94  28.1  0.167   21      0
4       0   137    40    35   168  43.1  2.288   33      1
..    ...   ...   ...   ...   ...   ...    ...  ...    ...
763    10   101    76    48   180  32.9  0.171   63      0
764     2   122    70    27     0  36.8  0.340   27      0
765     5   121    72    23   112  26.2  0.245   30      0
766     1   126    60     0     0  30.1  0.349   47      1
767     1    93    70    31     0  30.4  0.315   23      0

[768 rows x 9 columns]

In [ ]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

In [ ]:
filename = "/content/pima-indians-diabetes.data.csv"

In [ ]:
names = ["preg","plas","pres","skin","test","mass","pedi","age","class"]

In [ ]:
DataFrame= read_csv(filename,names=names)
array = DataFrame.values

In [ ]:
X = array [:,0:8]
Y = array [:,8]
model = LogisticRegression(max_iter=400)
rfe = RFE(model)
fit = rfe.fit(X,Y)

In [ ]:
fit.n_features_

np.int64(4)

In [ ]:
fit.support_

array([ True,  True, False, False, False,  True,  True, False])

In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
fit.ranking_

array([1, 1, 3, 5, 4, 1, 1, 2])

In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']

In [ ]:
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier

In [ ]:
filename = "/content/pima-indians-diabetes.data.csv"

In [ ]:
names = ["preg","plas","pres","skin","test","mass","pedi","age","class"]

In [ ]:
DataFrame= read_csv(filename,names=names)
array = DataFrame.values

In [ ]:
X = array [:,0:8]
Y = array [:,8]
model = DecisionTreeClassifier()
model.fit(X,Y)
print(model.feature_importances_)

[0.0692 0.3119 0.1035 0.0166 0.0324 0.2185 0.1244 0.1235]


In [ ]:
sorted_list = model.feature_importances_
print("feature importance=", sorted_list)
sorted_list.sort()
print("sorted feature importance=", sorted_list)

feature importance= [0.0692 0.3119 0.1035 0.0166 0.0324 0.2185 0.1244 0.1235]
sorted feature importance= [0.0166 0.0324 0.0692 0.1035 0.1235 0.1244 0.2185 0.3119]


In [ ]:
names

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']