In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
1-(stats.t.cdf(2.2,df=79))

np.float64(0.015364507770762481)

In [5]:
r=1-stats.t.cdf(1.4,49)
p=r*2
p

np.float64(0.16781331091681295)

In [6]:
r=stats.t.cdf(-1.4,79)
p=r*2
p

np.float64(0.1654283241373675)

In [9]:
r=2*stats.t.cdf(-1.4,49)
print(r)
#print(round(r,4))

0.16781331091681306


In [10]:
t = (4.0-4)/(3/np.sqrt(50))
t

np.float64(0.0)

In [11]:
p=2*stats.t.cdf(0,49)
p

np.float64(1.0)

In [12]:
data = pd.DataFrame([0.593,0.142,0.329,0.691,0.231,0.793,0.519,0.392,0.418])

In [13]:
data

0
0  0.593
1  0.142
2  0.329
3  0.691
4  0.231
5  0.793
6  0.519
7  0.392
8  0.418

In [14]:
stats.ttest_1samp(data,0.3)

TtestResult(statistic=array([2.20505884]), pvalue=array([0.05853033]), df=array([8]))

In [15]:
p=stats.ttest_1samp(data,0.3)[1]
p

array([0.05853033])

In [16]:
p_value=p/2
p_value

array([0.02926516])

In [17]:
control = pd.Series([91,87,99,77,88,91])
Treat = pd.Series([101,110,103,93,99,104])

In [18]:
stats.ttest_ind(control,Treat)

TtestResult(statistic=np.float64(-3.4456126735364876), pvalue=np.float64(0.006272124350809803), df=np.float64(10.0))

In [19]:
n1 = 247
p1 = .37

n2 = 308
p2 = .39

sample1 = np.random.binomial(1,p1,n1)

In [20]:
sample1

array([0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1])

In [21]:
len(sample1)

247

In [22]:
sample1.mean()

np.float64(0.3684210526315789)

In [23]:
sample2 = np.random.binomial(1,p2,n2)

In [24]:
sample2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,

In [25]:
len(sample2)

308

In [31]:
sample2.mean()

np.float64(0.31493506493506496)

In [27]:
import statsmodels.api as sm

In [30]:
p = sm.stats.ttest_ind(sample1,sample2)[1]
print(p)
print(round(p,4))

0.18644225112291837
0.1864


In [32]:
a = 0.05
if p > a:
  print(f"Accept null hypothesis.\n---------------")
else:
  print(f"Accept alternative hypothesis.\n------------")

Accept null hypothesis.
---------------


In [34]:
a = 0.05
sample1 = np.random.binomial(1,p1,n1)
sample2 = np.random.binomial(1,p2,n2)
p = sm.stats.ttest_ind(sample1,sample2)[1]
print(p)
print(round(p,4))
if p > a:
  print(f"Accept null hypothesis.\n---------------")
else:
  print(f"Accept alternative hypothesis.\n------------")

0.6060683067444799
0.6061
Accept null hypothesis.
---------------
